### ISSUE TITLE
Inconsistency in Arxiv compilation 

### ISSUE THREAD

**Issue by yoavartzi** [acl-org/acl-style-files#14]
Not exactly sure about the technical details. We encountered issues with fonts that caused previously unseen overflow when submitting to Arxiv. Maybe it was with caption and abstract fonts. Tax version on overleaf was 2021. I believe this is the version Arxiv runs as well.

**Comment by danielgildea** [comment]
Do you have `\pdfoutput=1` in the first five lines of your .tex?  This is necessary to tell arxiv to use pdflatex.

If yes, can you provide a example tex file showing the problem?

**Comment by yoavartzi** [comment]
It's on line 7, but I am not sure if you count comments/empty lines
<img width="885" alt="image" src="https://user-images.githubusercontent.com/3289873/208519645-339f5510-38a7-4bbb-92b2-3bb3c0a224f4.png">

**Comment by danielgildea** [comment]
I think it really needs to be in the first 5 lines.  Closing, please reopen if there is still a problem.
