### ISSUE TITLE
Have to move files before being able to use pdflatex

### ISSUE THREAD

**Issue by robvanderg** [acl-org/acl-style-files#28]
If a new "user" clones the repo and wants to get started with pdflatex and the acl_latex.tex file it can be a bit confusing. The acl_natbib.bst has to be moved to the root of the repo, or the acl_latex.tex + custom.bib into the latex folder for it to run pdflatex/bibtex successfully. Confusion could be avoided if these are moved in the repo already. Not sure what the preferred location is, I guess everything that is latex in the latex folder?, except if its desirable to prioritize the latex ones, then it might make sense to move the contents of the latex folder to the root.

**Comment by davidweichiang** [comment]
Sorry, I agree this is a problem and it's probably my fault. The simplest thing to do would be to move `acl_latex.tex` back into the `latex` subdirectory. I thought that might be disorienting for Overleaf users, but it looks like that's how it's already set up on Overleaf!
