### ISSUE TITLE
Sync with Overleaf

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/acl-style-files#6]
Who maintains the Overleaf version and can keep it in sync with this version? @neubig @bethard @mjpost

The recent changes are not critical, but it would be good to know who to contact when there is a critical change.

**Comment by mjpost** [comment]
Good question, I'm not sure. I'm not sure if tagging here will work, you might want to email.

**Comment by neubig** [comment]
I also don't know, it's not me.

**Comment by davidweichiang** [comment]
It looks like @mjpost is the owner. Also, it appears that I can edit it -- I hope it's not world-editable -- is it?

**Comment by davidweichiang** [comment]
Also, it looks to me like this is an ordinary project and not a template?

**Comment by mjpost** [comment]
That is the draft template I created when we were fiddling around with the new environment. I did not realize this got converted into the official template!

**Comment by davidweichiang** [comment]
I think it would be nice to create an Overleaf template that is linked to this GitHub repository. Then any updates here can be synced to Overleaf with one click.

Like this (demo, don't actually use): https://www.overleaf.com/read/yrqgpvyrscxj

**Comment by davidweichiang** [comment]
@mjpost Do you know who we would contact in order to get permissions to import from this repo to Overleaf?

**Comment by davidweichiang** [comment]
Someone made this on Dec 9: https://www.overleaf.com/latex/templates/acl-rolling-review-template/jxbhdzhmcpdm

**Comment by davidweichiang** [comment]
Publishing a template requires moderation by Overleaf and I'm not sure what the process is for updating an existing template. Maybe it should remain an ordinary project after all. The only downside I see is that users have to take the extra step of cloning the project (which they currently have to do, and should be documented).

**Comment by davidweichiang** [comment]
@ajstent @neubig Do you have any thoughts about this?

**Comment by ajstent** [comment]
not only does publishing a template require Overleaf moderation, but then it's really really hard to get them to unpublish it. So I'd suggest not, thanks though!

**Comment by davidweichiang** [comment]
OK, so I can think of two options:

(1) Continue using @mjpost's project and manually re-upload the style files whenever they change.

Pros: Status quo, simple

Cons: Re-uploading is more work, and someone with write permissions on the repository might not have write permissions on Overleaf

(2) Create a new Overleaf project (not template) that is set up to sync with this repository.

Pros: Syncing is a one-button process 

Cons:
- We'll need the owner of this Github organization to do the linking to Overleaf, or give someone permission to do it.
- The actual LaTeX template will be in a subdirectory, which will be inconvenient for authors.

**Comment by davidweichiang** [comment]
> Can this be done via cron job, daily, using Overleaf's git offering?

I don't think that's necessary; I believe an Overleaf project can be set up to use the official git repository as its underlying repository, so it would all be automatic.

The fact that the LaTeX files would be in a subdirectory seems to me an annoying problem, though, enough to make me favor (1).

**Comment by davidweichiang** [comment]
The other question you brought up about ARR is a good one but should be made by the ARR editors. As far as maintaining the style files is concerned, I suggest we use some kind of semantic versioning (major version = can affect accept/reject decisions; minor version = improvements that don't affect accept/reject) and ARR, or any meetings not using ARR, can decide to require a minimum version number.

**Comment by davidweichiang** [comment]
Maybe better than a cron job would be a GitHub action that, whenever there is a push on this repository, pushes the `latex/` subdirectory into the Overleaf repository. I don't know how to do that, but maybe you or @mjpost can do it (especially since @mjpost owns the current Overleaf project).

**Comment by ajstent** [comment]
From an ARR perspective, we point authors to the current official version; venues (conferences, workshops) would be the ones to potentially see papers using older templates. (Wouldn't it be nice if we could just have authors upload the LaTex like arXiv does? long-term future work). I think for now ARR just continues to point authors at the official repository.

**Comment by jkkummerfeld** [comment]
Reviving this discussion - the repository and the Overleaf version are not in sync yet. Skimming the discussion above, it sounds like that is something only @mjpost can fix?

**Comment by mjpost** [comment]
I just shared with a number of you an Overleaf project that I think has been used for some conferences. I think this has been used at least once, but I don't know for what conference. It's hard to know who's using what.

It shouldn't be too hard to set this up to automatically update; the harder item is to adopt and enforce a policy where people across conferences stick to using it.

**Comment by mjpost** [comment]
Also, I just checked, and this might be easier than we had hoped—Overleaf has an explicit option to sync with a named Github repo. It looks like I don't have the right permissions to acl-org, though.

@jkkummerfeld do you what is the current correct version? Is it this repo, or the current template?

**Comment by jkkummerfeld** [comment]
ARR simply points to this repository. I just checked for ACL 2023, and it had a zip file. Comparing the contents of that zip file with this repository and overleaf I see:

acl_natbib.bst - same everywhere
acl.sty - the ACL 2023 version is closer to the overleaf version. There is one extra line `\newcommand{\citeposs}[1]{\citeauthor{#1}'s (\citeyear{#1})}` on line 210
 acl_latex.tex - The ACL 2023 version has a range of edits, including adding content about the Limitations section and Ethics Statement

Maybe the best thing is to update this repository and overleaf to match ACL 2023? (without the year specific bits) I'm happy to prepare the files and make a PR here if that's the right next step.

**Comment by mjpost** [comment]
Reviewing this thread I see David made the exact point about Github-backed Overleaf. 

I don't know about updating the repo with your suggested edits (I suppose you have jurisdiction here?) It seems reasonable. So a PR would be great. 

Then we should definitely connect this repo to the overleaf. This might be a job for @desilinguist.

**Comment by davidweichiang** [comment]
+1 for `\citeposs`.

**Comment by jkkummerfeld** [comment]
PR created - https://github.com/acl-org/acl-style-files/pull/18

**Comment by jkkummerfeld** [comment]
Re: jurisdiction... it's unclear to me who has definitive say here, since this is intended to be for general use within ACL. These edits don't seem substantive to me (just bringing in minor edits from ACL 2023 and updating the files to be consistent with standard practise re: limitations and ethics). Given that, I would assume anyone with PR-merging privileges in this repository can merge it.

**Comment by jkkummerfeld** [comment]
Following up on this. @danielgildea and @davidweichiang, based on our discussion in the PR, this repository is correct and the overleaf is out of date.

I have updated the overleaf content to match this repository (solution (1) above). That means all is well for the immediate next cycles of ARR (ie, for EACL, NAACL, and ACL). There is still the question of a longer term solution to keeping these in sync.

**Comment by danielgildea** [comment]
Since the github README points to the overleaf project, they should really be in sync.  Can you please update the overleaf project manually for now?

**Comment by mjpost** [comment]
Someone who's a member of @acl-org-github could easily link this directly from Overleaf. I don't seem to have the right permissions.

![image](https://github.com/acl-org/acl-style-files/assets/455256/31f0efca-bce1-4da7-beb9-b98f25bfa7c3)

**Comment by danielgildea** [comment]
I don't understand exactly what you're trying to do... the pasted graphic says "create a github repository", but we don't want to do that, we want to sync with this existing github repository, right?  What does acl-org-github own exactly? Do you have any idea who they are?

In any case, I think we should remove the link to overleaf from the README in github if we can't update the overleaf project.

**Comment by mjpost** [comment]
Yeah, I was assuming there would be a way to try to sync it with an existing Github repo, and included the screenshot just to demonstrate what it looks like for me. Digging a bit further, [the documentation tells how to do what we want](https://www.overleaf.com/learn/how-to/Git_integration#:~:text=Creating%20an%20Overleaf%20project%20from%20an%20existing%20Git,it%20into%20your%20master%20branch.%20...%20More%20items) (see "Creating an Overleaf project from an existing Git repository").

Since I own the Overleaf, I'll give this a shot.

**Comment by mjpost** [comment]
Okay, I updated the style files in the Overleaf template.

I didn't setup direct sync, because it would require the LaTeX style files to be moved to the root folder. If we want to do that, it should be trivial to setup the syncing. I would also suggest that we remove the `archive/` directory, since it will just clutter up people's directories. It's in the git history, anyway. If people care about quick access, we could add a "History" section to the README with direct links to the git commits.

**Comment by davidweichiang** [comment]
I agree about removing `archive`.

I think it might be okay either to change the example paper to `\usepackage{latex/acl}` or to leave the style files where they are and put a `latexmkrc` in the root directory (https://www.overleaf.com/learn/latex/Questions/I_have_a_lot_of_.cls%2C_.sty%2C_.bst_files%2C_and_I_want_to_put_them_in_a_folder_to_keep_my_project_uncluttered._But_my_project_is_not_finding_them_to_compile_correctly).

**Comment by mjpost** [comment]
@davidweichiang it's not quite what you asked for, but I created a PR at #19.

**Comment by danielgildea** [comment]
I merged the pull request.

Matt, can you please sync to overleaf again?

It looks like there is no way to make updates to overleaf totally automatic - we will need to push to overleaf for each change.  Could you add me as an owner of the overleaf project?

**Comment by mjpost** [comment]
Dan, I just added you to the Overleaf. I think we can make it automatic (see my post above on Sep. 12), but it just requires us to restructure the repo a bit so it makes sense in both settings. It'd be nice to keep both this repo and the current Overleaf since they are both pointed to from multiple places. I've not had time/motivation for this and am only accidentally involved so I'd be happy to have someone take it over.

**Comment by danielgildea** [comment]
Thanks, I have synched the overleaf and github repositories, and I can keep them in sync from now on.

(I haven't found a way to make this fully automatic.  I am doing "git push origin master" and "git push overleaf master" from the command line. Others with access to both repositories can do this too.  It looks like even with overleaf's sync with github feature, you would have to click a button to make the updates copy over.)

Matt, you can transfer ownership of the overleaf project to me if you want to be totally done with it.

**Comment by mjpost** [comment]
@danielgildea do you know who owns the ARR Overleaf (#37)? That one is not being updated (and contains outdated instructions about anthology.bib.gz).
